# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name = "gir_ffi-gtk4"
  s.version = "0.0.1"
  s.required_ruby_version = ">= 2.5.0"

  s.summary = "GirFFI-based Ruby bindings for Gtk+ 4"
  s.description = "Bindings for Gtk+ 4, generated by GirFFI, with overrides."
  s.license = "LGPL-2.1+"

  s.authors = ["Matijs van Zuijlen"]
  s.email = ["matijs@matijs.net"]
  s.homepage = "http://www.github.com/mvz/gir_ffi-gtk4"

  s.files =
    Dir["{lib,test,tasks,examples}/**/*", "*.md", "Rakefile", "COPYING.LIB"] &
    `git ls-files -z`.split("\0")
  s.test_files = `git ls-files -z -- test`.split("\0")

  s.add_runtime_dependency("gir_ffi", ["~> 0.15.3"])
  s.add_development_dependency("minitest", ["~> 5.12"])
  s.add_development_dependency("rake", ["~> 13.0"])
  s.add_development_dependency("rr", ["~> 3.0"])

  s.require_paths = ["lib"]
end
