# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "gir_ffi-gtk4"
  spec.version = "0.0.1"

  spec.authors = ["Matijs van Zuijlen"]
  spec.email = ["matijs@matijs.net"]

  spec.summary = "GirFFI-based Ruby bindings for Gtk+ 4"
  spec.description = "Bindings for Gtk+ 4, generated by GirFFI, with overrides."
  spec.homepage = "http://www.github.com/mvz/gir_ffi-gtk4"
  spec.license = "LGPL-2.1+"

  spec.required_ruby_version = ">= 2.6.0"

  spec.files =
    Dir["{lib,test,tasks,examples}/**/*", "*.md", "Rakefile", "COPYING.LIB"] &
    `git ls-files -z`.split("\0")
  spec.test_files = `git ls-files -z -- test`.split("\0")

  spec.add_runtime_dependency("gir_ffi", ["~> 0.15.3"])
  spec.add_development_dependency("minitest", ["~> 5.12"])
  spec.add_development_dependency("rake", ["~> 13.0"])
  spec.add_development_dependency("rr", ["~> 3.0"])

  spec.require_paths = ["lib"]
end
